// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgQ7JZEoJ2FR-kh3MUpvhTRPXDEMr5txs',
    appId: '1:926017391118:web:fc469ef3084360560b8a5f',
    messagingSenderId: '926017391118',
    projectId: 'kostraktor-c1716',
    authDomain: 'kostraktor-c1716.firebaseapp.com',
    storageBucket: 'kostraktor-c1716.firebasestorage.app',
    measurementId: 'G-XPVGTXEVSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrl6ElcP-iLYWYyRcRsDPsgwOh2XvC_-I',
    appId: '1:926017391118:android:f6b5efb1fceb8a320b8a5f',
    messagingSenderId: '926017391118',
    projectId: 'kostraktor-c1716',
    storageBucket: 'kostraktor-c1716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrgsTiqvhGXBJ9JWZJ_WpYjNWX_W4Tl5Q',
    appId: '1:926017391118:ios:c089e324e55ff4820b8a5f',
    messagingSenderId: '926017391118',
    projectId: 'kostraktor-c1716',
    storageBucket: 'kostraktor-c1716.firebasestorage.app',
    iosClientId: '926017391118-ok5n6rrev0cadmh3caqvevkl6kvike9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.kostraktor',
  );
}
